NTTB GELRE/Models/EditInschrijving.cs
namespace NTTB_GELRE.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Linq;
    using System.Web;

    public class EditInschrijving
    {

        public int SpelerID { get; set; }

        public long ToernooiID { get; set; }

        public int CategorieID { get; set; }

        public string Toernooinaam { get; set; }

        public DateTime Begindatum { get; set; }

        public DateTime Einddatum { get; set; }

        public string EnkelDubbel { get; set; }

        public string Licentie { get; set; }

        public DateTime EindInschrijving { get; set; }

    }

    
}

NTTB GELRE/Models/Inschrijvingen.cs
namespace NTTB_GELRE.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System;
    using System.Linq;
    using System.Web;

    public class Inschrijvingen
    {

        public int SpelerID { get; set; }

        public long ToernooiID { get; set; }

        public int CategorieID { get; set; }

        public string Toernooinaam { get; set; }

        public DateTime Begindatum { get; set; }

        public DateTime Einddatum { get; set; }

        public string EnkelDubbel { get; set; }

        public string Licentie { get; set; }

        public DateTime EindInschrijving { get; set; }

    }

    
}

NTTB GELRE/Controllers/SpelergegevensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NTTB_GELRE.Models;
using System.Data.SqlClient;

namespace NTTB_GELRE.Controllers
{
    public class SpelergegevensController : Controller
    {
        private NTTBGELREEntities db = new NTTBGELREEntities();

        // GET: Spelergegevens
        public ActionResult Index()
        {
            var SessionSpelerID = Session["spelerID"];

            ViewBag.SpelerID = SessionSpelerID;

            return View();
        }


        // GET: Spelergegevens/ZoekSpeler
        public ActionResult ZoekSpeler(string mailadres, string voornaam, string tussenvoegsel, string achternaam, DateTime? geboortedatum, int bondsnummer = 0)
        {
            var RolWerknemer = "Administratie";

            if (RolWerknemer == "Administratie")
            {

                var spelers = (from s in db.Speler
                               select s);

                // Filter by bondsnummer
                if (bondsnummer > 0)
                {
                    spelers = spelers.Where(v => v.Bondsnummer == (bondsnummer));
                }

                // Filter by mailadres
                if (!String.IsNullOrEmpty(mailadres))
                {
                    spelers = spelers.Where(n => n.Mailadres.Contains(mailadres));
                }

                // Filter by voornaam
                if (!String.IsNullOrEmpty(voornaam))
                {
                    spelers = spelers.Where(n => n.Voornaam.Contains(voornaam));
                }

                // Filter by tussenvoegsel
                if (!String.IsNullOrEmpty(tussenvoegsel))
                {
                    spelers = spelers.Where(n => n.Tussenvoegsel.Contains(tussenvoegsel));
                }

                // Filter by achternaam
                if (!String.IsNullOrEmpty(achternaam))
                {
                    spelers = spelers.Where(n => n.Achternaam.Contains(achternaam));
                }

                // Filter by geboortedatum
                if (geboortedatum.HasValue)
                {
                    spelers = spelers.Where(v => v.Geboortedatum == (geboortedatum));
                }

                return View(spelers);

            }
            else
            {
                return View();
            }

        }


        // GET: Spelergegevens/EditPersoonsgegevens/5
        public ActionResult EditPersoonsgegevens(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Speler speler = db.Speler.Find(id);
            if (speler == null)
            {
                return HttpNotFound();
            }

            // Geslacht combobox waardes
            var geslachten = new List<SelectListItem>()
            {
                new SelectListItem {Value = "M", Text = "Man"},
                new SelectListItem {Value = "V", Text = "Vrouw"}
            };

            ViewBag.geslacht = new SelectList(geslachten, "Value", "Text");

            // Licentie combobox waardes
            var licenties = new List<SelectListItem>()
            {
                new SelectListItem {Value = "A", Text = "A"},
                new SelectListItem {Value = "B", Text = "B"},
                new SelectListItem {Value = "C", Text = "C"},
                new SelectListItem {Value = "D", Text = "D"},
                new SelectListItem {Value = "E", Text = "E"},
                new SelectListItem {Value = "F", Text = "F"},
            };

            ViewBag.licentie = new SelectList(licenties, "Value", "Text");

            return View(speler);
        }


        // POST: Spelergegevens/EditPersoonsgegevens/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPersoonsgegevens([Bind(Exclude = "Wachtwoord,WachtwoordSalt")] Speler speler)
        {
            if (ModelState.IsValid)
            {

                // Stored procedure
                NTTBGELREEntities ctx = new NTTBGELREEntities();
                System.Data.Common.DbConnection dbConn = ctx.Database.Connection;
                System.Data.SqlClient.SqlConnection sc = (System.Data.SqlClient.SqlConnection)dbConn;
                string adoConnStr = sc.ConnectionString;

                using (SqlConnection connection = new SqlConnection(adoConnStr))
                {
                    connection.Open();
                    // Stored procedure naam = spInschrijvingSpelerZonderAccount
                    SqlCommand cmd = new SqlCommand("spEditSpelergegevens", connection);
                    cmd.CommandType = CommandType.StoredProcedure;

                    // Paramaters voor de stored procedure
                    cmd.Parameters.AddWithValue("@spelerID", speler.SpelerID);
                    cmd.Parameters.AddWithValue("@voornaam", speler.Voornaam);
                    cmd.Parameters.AddWithValue("@tussenvoegsel", speler.Tussenvoegsel);
                    cmd.Parameters.AddWithValue("@achternaam", speler.Achternaam);
                    cmd.Parameters.AddWithValue("@bondsnummer", speler.Bondsnummer);
                    cmd.Parameters.AddWithValue("@geboortedatum", speler.Geboortedatum);
                    cmd.Parameters.AddWithValue("@geslacht", speler.Geslacht);
                    cmd.Parameters.AddWithValue("@telefoonnummer", speler.Telefoonnummer);
                    cmd.Parameters.AddWithValue("@mailadres", speler.Mailadres);
                    cmd.Parameters.AddWithValue("@licentie", speler.Licentie);
                    cmd.Parameters.AddWithValue("@punten", speler.Punten);

                    cmd.ExecuteNonQuery();
                }

                // Inschrijving succesvol
                ViewBag.SuccessMessage = "Uw gegevens zijn succesvol aangepast";
                return View("Succes");
            }

            // Er ging iets mis
            ViewBag.Error = "Er ging iets mis, probeer het later nog eens";
            return RedirectToAction("Index", new { id = speler.SpelerID });

        }


        // GET: Spelergegevens/Inschrijvingen/5
        public ActionResult Inschrijvingen(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Speler speler = db.Speler.Find(id);
            if (speler == null)
            {
                return HttpNotFound();
            }

            var inschrijvingen = (from d in db.Deelnemer
                                  join c in db.Categorie on d.CategorieID equals c.CategorieID
                                  join t in db.Toernooi on d.ToernooiID equals t.ToernooiID
                                  where d.SpelerID == id
                                  orderby t.Begindatum
                                  select new Inschrijvingen { ToernooiID = d.ToernooiID, CategorieID = c.CategorieID, SpelerID = d.SpelerID, Toernooinaam = t.Toernooinaam, Begindatum = t.Begindatum, Einddatum = t.Einddatum, EnkelDubbel = c.EnkelDubbel, Licentie = c.Niveau, EindInschrijving = t.EindInschrijving });
            
            return View(inschrijvingen);
        }


        // GET: Spelergegevens/EditInschrijving/5
        public ActionResult EditInschrijving(int? toernooiID, int? categorieID, int? spelerID)
        {
            if (toernooiID == null || categorieID == null || spelerID == null )
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var inschrijving = (from d in db.Deelnemer
                                join c in db.Categorie on d.CategorieID equals c.CategorieID
                                join t in db.Toernooi on d.ToernooiID equals t.ToernooiID
                                where d.SpelerID == spelerID
                                   && d.CategorieID == categorieID
                                   && d.ToernooiID == toernooiID
                                select new Inschrijvingen { ToernooiID = d.ToernooiID, CategorieID = c.CategorieID, SpelerID = d.SpelerID, Toernooinaam = t.Toernooinaam, Begindatum = t.Begindatum, Einddatum = t.Einddatum, EnkelDubbel = c.EnkelDubbel, Licentie = c.Niveau, EindInschrijving = t.EindInschrijving }).SingleOrDefault();

            return View(inschrijving);
        }


        // POST: Spelergegevens/EditInschrijving/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditInschrijving(Inschrijvingen inschrijving)
        {
            if (ModelState.IsValid)
            {

                // Stored procedure
                NTTBGELREEntities ctx = new NTTBGELREEntities();
                System.Data.Common.DbConnection dbConn = ctx.Database.Connection;
                System.Data.SqlClient.SqlConnection sc = (System.Data.SqlClient.SqlConnection)dbConn;
                string adoConnStr = sc.ConnectionString;

                using (SqlConnection connection = new SqlConnection(adoConnStr))
                {
                    connection.Open();
                    // Stored procedure naam = spEditInschrijving
                    SqlCommand cmd = new SqlCommand("spEditInschrijving", connection);
                    cmd.CommandType = CommandType.StoredProcedure;

                    // Paramaters voor de stored procedure
                    cmd.Parameters.AddWithValue("@toernooiID", inschrijving.ToernooiID);
                    cmd.Parameters.AddWithValue("@categorieID", inschrijving.CategorieID);
                    cmd.Parameters.AddWithValue("@spelerID", inschrijving.SpelerID);

NTTB GELRE/Views/Spelergegevens/DeleteInschrijving.cshtml
@model NTTB_GELRE.Models.Inschrijvingen

@{
    ViewBag.Title = "Delete inschrijving";
}

<h2>Delete inschrijving</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Toernooi</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Toernooinaam)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Toernooinaam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Begindatum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Begindatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Einddatum)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Einddatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnkelDubbel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EnkelDubbel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Licentie)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Licentie)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Uitschrijven" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NTTB GELRE/Views/Spelergegevens/EditInschrijving.cshtml
@model NTTB_GELRE.Models.Inschrijvingen

@{
    ViewBag.Title = "Inschrijving wijzigen";
}

<h2>Inschrijving wijzigen</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Speler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.SpelerID)
        @Html.HiddenFor(model => model.ToernooiID)

        <div class="form-group">
            @Html.LabelFor(model => model.Toernooinaam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Toernooinaam)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Begindatum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Begindatum)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Einddatum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Einddatum)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnkelDubbel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.DisplayFor(model => model.EnkelDubbel)
                @Html.ValidationMessageFor(model => model.EnkelDubbel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Licentie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Licentie, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Licentie, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NTTB GELRE/Views/Spelergegevens/EditPersoonsgegevens.cshtml
@model NTTB_GELRE.Models.Speler

@{
    ViewBag.Title = "Persoonsgegevens";
}

<h2>Persoonsgegevens</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Speler</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SpelerID)

        <div class="form-group">
            @Html.LabelFor(model => model.Voornaam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Voornaam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Voornaam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tussenvoegsel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tussenvoegsel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tussenvoegsel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Achternaam, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Achternaam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Achternaam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bondsnummer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.EditorFor(model => model.Bondsnummer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bondsnummer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Geboortedatum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Geboortedatum, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.Geboortedatum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Geslacht, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.DropDownList("geslacht", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Geslacht, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mailadres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mailadres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mailadres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefoonnummer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefoonnummer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefoonnummer, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Wachtwoord, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Wachtwoord, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Wachtwoord, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WachtwoordSalt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WachtwoordSalt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WachtwoordSalt, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Licentie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.DropDownList("licentie", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Licentie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Punten, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-2">
                @Html.EditorFor(model => model.Punten, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Punten, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NTTB GELRE/Views/Spelergegevens/Index.cshtml
@{
    ViewBag.Title = "Speleraccount";
}

<h2>Speleraccount</h2>

@Html.ActionLink("Persoonsgegevens", "EditPersoonsgegevens", new { id = ViewBag.SpelerID }, new { @class = "btn btn-default" })
@Html.ActionLink("Inschrijvingen", "Inschrijvingen", new { id = ViewBag.SpelerID }, new { @class = "btn btn-default" })

NTTB GELRE/Views/Spelergegevens/Inschrijvingen.cshtml
@model IEnumerable<NTTB_GELRE.Models.Inschrijvingen>

@{
    ViewBag.Title = "Inschrijvingen";
}

<h2>Inschrijvingen</h2>


    
    <table class="table">

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Toernooinaam)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Begindatum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Einddatum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EnkelDubbel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Licentie)
            </th>

        </tr>

        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Toernooinaam)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Begindatum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Einddatum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EnkelDubbel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Licentie)
                </td>
                <td>
                    @if (item.EindInschrijving > DateTime.Today)
                    {
                        @Html.ActionLink("Uitschrijven", "DeleteInschrijving", new { @toernooiID = item.ToernooiID, @categorieID = item.CategorieID, @spelerID = item.SpelerID }, new { @class = "btn btn-default" })
                    }
                </td>


                <td>
                    @if (Session["Rol"].ToString() == "Administratie")
                    {
                        @Html.ActionLink("Edit", "EditInschrijving", new { @toernooiID = item.ToernooiID, @categorieID = item.CategorieID, @spelerID = item.SpelerID }, new { @class = "btn btn-default" })
                    }
                    
                </td>

            </tr>
        }



</table>
    

    <div>
        @Html.ActionLink("Terug", "Index", null, new { @class = "btn btn-default" })
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

NTTB GELRE/Views/Spelergegevens/Succes.cshtml
@{
    ViewBag.Title = "Success";
}

<h2>@ViewBag.SuccessMessage</h2>

<p>Klik <u>@Html.ActionLink("hier", "Index", "Home")</u> om terug te gaan naar de hoofdpagina</p>

NTTB GELRE/Views/Spelergegevens/ZoekSpeler.cshtml
@model IEnumerable<NTTB_GELRE.Models.Speler>

@{
    ViewBag.Title = "Speler Zoeken";
}

<h2>Speler Zoeken</h2>

@using (Html.BeginForm("ZoekSpeler", "Spelergegevens", FormMethod.Get))
{
    <table>
        <tr>
            <td>Bondsnummer: @Html.TextBox("bondsnummer")</td>
            <td>E-mail adres: @Html.TextBox("mailadres")</td>
        </tr>
        <tr>
            <td>Voornaam: @Html.TextBox("voornaam")</td>
            <td>Tussenvoegsel: @Html.TextBox("tussenvoegsel")</td>
            <td>Achternaam: @Html.TextBox("achternaam")</td>
            <td>Geboortedatum:@Html.Editor("geboortedatum", new { htmlAttributes = new { @class = "form-control datepicker" } })</td>
</tr>
    </table>
    <input type="submit" value="Zoek" />
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Bondsnummer")
        </th>
        <th>
            @Html.DisplayName("E-mail adres")
        </th>
        <th>
            @Html.DisplayName("Naam")
        </th>
        
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Bondsnummer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mailadres)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Voornaam) 
                @Html.DisplayFor(modelItem => item.Tussenvoegsel) 
                @Html.DisplayFor(modelItem => item.Achternaam)
            </td>
            <td>
                @Html.ActionLink("Inschrijvingen", "Inschrijvingen", new { id = item.SpelerID }, new { @class = "btn btn-default" })
            </td>
        </tr>
    }

</table>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

    <script>
    $(document).ready(function () {
    $(".datepicker").datepicker({
        dateFormat: 'yy-mm-dd',
        changeMonth: true,
        changeYear: true,
        yearRange: '-150:+0'
    });

    });
    </script>

}