NTTB GELRE/Models/Categorie.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTTB_GELRE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public Categorie()
        {
            this.Toernooicategorie = new HashSet<Toernooicategorie>();
        }
    
        public int CategorieID { get; set; }
        public string Leeftijdsgroep { get; set; }
        public string Subcategorie { get; set; }
        public string EnkelDubbel { get; set; }
        public string Geslacht { get; set; }
        public string Niveau { get; set; }
    
        public virtual ICollection<Toernooicategorie> Toernooicategorie { get; set; }
    }
}

NTTB GELRE/Controllers/CategorieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NTTB_GELRE.Models;
using System.Diagnostics;

namespace NTTB_GELRE.Controllers
{
    public class CategorieController : Controller
    {
        private NTTBGELREEntities db = new NTTBGELREEntities();

        public ActionResult AddCatToDeelschema(long? id)
        {
            Debug.WriteLine(id);
            return RedirectToAction("categorieList");
          
        }
      
        // GET: Categorie
        public ActionResult Index(long? id)
        {
   
            return View(db.Categorie.ToList());
        }

         [HttpGet]
        public ActionResult categorieList(long? id)
        {
            ViewBag.ToernooiID = id;
            ViewBag.Toernooivorm = new SelectList(db.Toernooivorm, "Toernooivorm1", "Toernooivorm1");
            //var query = (from c in db.Categorie
            //             join ts in db.Toernooischema on c.CategorieID equals ts.CategorieID                          
            //             where  ts.ToernooiID == 1
            //             select new { c.Leeftijdsgroep,c.Subcategorie, c.EnkelDubbel, c.Geslacht,c.Niveau });

            //var cat = new List<Categorie>();
            //foreach (var t in query)
            //{
            //    cat.Add(new Categorie()
            //    {
            //        Leeftijdsgroep = t.Leeftijdsgroep,
            //        Subcategorie = t.Subcategorie,
            //        EnkelDubbel = t.EnkelDubbel,
            //        Geslacht = t.Geslacht,
            //        Niveau = t.Niveau
            //    });
            //}
            return View(db.Categorie.ToList());
        }

        // GET: Categorie/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categorie categorie = db.Categorie.Find(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }
     


        // GET: Categorie/Create
        public ActionResult Create( )
        {

            return View();
        }

        // POST: Categorie/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategorieID,Leeftijdsgroep,Subcategorie,EnkelDubbel,Geslacht,Niveau")] Categorie categorie)
        {
            if (ModelState.IsValid)
            {
                db.Categorie.Add(categorie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categorie);
        }

        // GET: Categorie/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categorie categorie = db.Categorie.Find(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // POST: Categorie/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategorieID,Leeftijdsgroep,Subcategorie,EnkelDubbel,Geslacht,Niveau")] Categorie categorie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categorie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categorie);
        }

        // GET: Categorie/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categorie categorie = db.Categorie.Find(id);
            if (categorie == null)
            {
                return HttpNotFound();
            }
            return View(categorie);
        }

        // POST: Categorie/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Categorie categorie = db.Categorie.Find(id);
            db.Categorie.Remove(categorie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NTTB GELRE/Controllers/ToernooiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NTTB_GELRE.Models;
using System.Data.SqlClient;
using System.Data.Entity.Core.EntityClient;
using System.Configuration;
using System.Web.SessionState;

namespace NTTB_GELRE.Controllers
{
    public class ToernooiController : Controller
    {
        private NTTBGELREEntities db = new NTTBGELREEntities();


        public ToernooiController(){

                   
         
        }
        // GET: Toernooi
        public ActionResult Index()
        {
            
            var toernoois = db.Toernooi.Include(t => t.Locatie).Include(t => t.Puntentelling);
            return View(toernoois.ToList());
        }

      
        // GET: Toernooi/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Toernooi toernooi = db.Toernooi.Find(id);
            if (toernooi == null)
            {
                return HttpNotFound();
            }
            return View(toernooi);
        }

        // GET: Toernooi/Create
        public ActionResult Create()
        {
            ViewBag.addCar = false;
            //ViewData["categorie"] = db.Categorie.ToList();
            ViewBag.Locatienaam = new SelectList(db.Locatie, "Locatienaam", "Locatienaam");

            
            //ViewBag.Locatienaam = new SelectList(db.Locatie, "Locatienaam", "Locatienaam");

            var leeftijdsgroepen = db.Categorie.Select(c => c.Leeftijdsgroep).Distinct();
            ViewBag.Categorie = new SelectList(leeftijdsgroepen);
       
            ViewBag.TellingID = new SelectList(db.Puntentelling, "TellingID", "Tot");

            List<SelectListItem> puntentellingen = new List<SelectListItem>();
            puntentellingen.Add(new SelectListItem { Text = "1", Value = "1" });
            puntentellingen.Add(new SelectListItem { Text = "3", Value = "3" });
            puntentellingen.Add(new SelectListItem { Text = "5", Value = "5" });
            puntentellingen.Add(new SelectListItem { Text = "7", Value = "7" });
            puntentellingen.Add(new SelectListItem { Text = "9", Value = "9" });
            puntentellingen.Add(new SelectListItem { Text = "11", Value = "11" });

            ViewBag.GewonnenGames = puntentellingen;

            var toernooivormenLst = new List<string>();

            var toernooivormenQry = (from t in db.Toernooivorm
                                     select t.Toernooivorm1);

            toernooivormenLst.AddRange(toernooivormenQry.Distinct());
            ViewBag.toernooivormen = new SelectList(toernooivormenLst);

            return View();
        }

        // POST: Toernooi/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ToernooiAanmaken toernooi)
        {
            if (ModelState.IsValid)
            {

                // Stored procedure
                NTTBGELREEntities ctx = new NTTBGELREEntities();
                System.Data.Common.DbConnection dbConn = ctx.Database.Connection;
                System.Data.SqlClient.SqlConnection sc = (System.Data.SqlClient.SqlConnection)dbConn;
                string adoConnStr = sc.ConnectionString;

                using (SqlConnection connection = new SqlConnection(adoConnStr))
                {
                    connection.Open();
                    // Stored procedure naam = inschrijving
                    SqlCommand cmd = new SqlCommand("spSchemasAanmaken", connection);
                    cmd.CommandType = CommandType.StoredProcedure;

                    // Paramaters voor de stored procedure
                    cmd.Parameters.AddWithValue("@Locatienaam", toernooi.Locatienaam);
                    cmd.Parameters.AddWithValue("@TellingID", toernooi.TellingID);
                    cmd.Parameters.AddWithValue("@Toernooinaam", toernooi.Toernooinaam);
                    cmd.Parameters.AddWithValue("@Begindatum", toernooi.Begindatum);
                    cmd.Parameters.AddWithValue("@Einddatum", toernooi.Einddatum);
                    cmd.Parameters.AddWithValue("@Inschrijfdatum", toernooi.Inschrijfdatum);
                    cmd.Parameters.AddWithValue("@InschrijfGeldEnkel", toernooi.InschrijfgeldEnkel);
                    cmd.Parameters.AddWithValue("@InschrijfGeldDubbel", toernooi.InschrijfgeldDubbel);
                    cmd.Parameters.AddWithValue("@Organisatie", toernooi.Organisatie);
                    cmd.Parameters.AddWithValue("@Bondsvertegenwoordiger", toernooi.Bondsvertegenwoordiger);
                    cmd.Parameters.AddWithValue("@GewonnenGames", toernooi.GewonnenGames);
                    cmd.Parameters.AddWithValue("@Tijdlimiet", toernooi.Tijdlimiet);
                    cmd.Parameters.AddWithValue("@Tafels", toernooi.Tafels);
                    cmd.Parameters.AddWithValue("@Categorie", toernooi.Categorie);
                    cmd.Parameters.AddWithValue("@Niveaus", toernooi.Niveaus);
                    cmd.Parameters.AddWithValue("@Toernooivorm1", toernooi.Toernooivorm1);
                    cmd.Parameters.AddWithValue("@Toernooivorm2", toernooi.Toernooivorm2);
                    cmd.Parameters.AddWithValue("@Toernooivorm3", toernooi.Toernooivorm3);
                    cmd.Parameters.AddWithValue("@Toernooivorm4", toernooi.Toernooivorm4);
                    
                    
                    cmd.ExecuteNonQuery();
                }

                return RedirectToAction("Index","Home");
            }
            ViewBag.Locatienaam = new SelectList(db.Locatie, "Locatienaam", "Locatienaam");


            //ViewBag.Locatienaam = new SelectList(db.Locatie, "Locatienaam", "Locatienaam");

            var leeftijdsgroepen = db.Categorie.Select(c => c.Leeftijdsgroep).Distinct();
            ViewBag.Categorie = new SelectList(leeftijdsgroepen);
            
            ViewBag.TellingID = new SelectList(db.Puntentelling, "TellingID", "Tot");
            List<SelectListItem> puntentellingen = new List<SelectListItem>();
            puntentellingen.Add(new SelectListItem { Text = "1", Value = "1" });
            puntentellingen.Add(new SelectListItem { Text = "3", Value = "3" });
            puntentellingen.Add(new SelectListItem { Text = "5", Value = "5" });
            puntentellingen.Add(new SelectListItem { Text = "7", Value = "7" });
            puntentellingen.Add(new SelectListItem { Text = "9", Value = "9" });
            puntentellingen.Add(new SelectListItem { Text = "11", Value = "11" });

            ViewBag.GewonnenGames = puntentellingen;

            var toernooivormenLst = new List<string>();

            var toernooivormenQry = (from t in db.Toernooivorm
                                     select t.Toernooivorm1);

            toernooivormenLst.AddRange(toernooivormenQry.Distinct());
            ViewBag.toernooivormen = new SelectList(toernooivormenLst);

            return View(toernooi);
        }

        // GET: Toernooi/CreateStepTwo
        public ActionResult CreateStepTwo(int toernooiID, string leeftijdsgroep)
        {
            var Categorieen = from c in db.Categorie
                              where c.Leeftijdsgroep == leeftijdsgroep
                              select c;
            return View(Categorieen.ToList());
        }

        // GET: Toernooi/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Toernooi toernooi = db.Toernooi.Find(id);
            if (toernooi == null)
            {
                return HttpNotFound();
            }
            ViewBag.Locatienaam = new SelectList(db.Locatie, "Locatienaam", "Adres", toernooi.Locatienaam);
            ViewBag.TellingID = new SelectList(db.Puntentelling, "TellingID", "TellingID", toernooi.TellingID);
            return View(toernooi);
        }

        // POST: Toernooi/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ToernooiID,Locatienaam,TellingID,Toernooinaam,Begindatum,Einddatum,Inschrijfdatum,InschrijfgeldEnkel,InschrijfgeldDubbel,Organisatie,Bondsvertegenwoordiger,GewonnenGames,Tijdlimiet,Tafels")] Toernooi toernooi)
        {
            if (ModelState.IsValid)
            {
                db.Entry(toernooi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
  
            ViewBag.Locatienaam = new SelectList(db.Locatie, "Locatienaam", "Adres", toernooi.Locatienaam);
            ViewBag.TellingID = new SelectList(db.Puntentelling, "TellingID", "TellingID", toernooi.TellingID);
            return View(toernooi);
        }

        // GET: Toernooi/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Toernooi toernooi = db.Toernooi.Find(id);
            if (toernooi == null)
            {
                return HttpNotFound();
            }
            return View(toernooi);
        }

        // POST: Toernooi/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Toernooi toernooi = db.Toernooi.Find(id);

NTTB GELRE/Views/Toernooi/Create.cshtml
@model NTTB_GELRE.Models.ToernooiAanmaken


<h2>Toernooi aanmaken</h2>

@using (Html.BeginForm("Create", "Toernooi", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()


    <div class="form-horizontal">
        <h4>Vul gegevens in</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="toernooiCreate">
            <div class="toernooiCreateLeft">
                <div class="form-group">
                    @Html.LabelFor(model => model.Toernooinaam, "Toernooinaam", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Toernooinaam, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Toernooinaam, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Locatienaam, "Locatie", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Locatienaam", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Locatienaam, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Begindatum, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Begindatum, new { htmlAttributes = new { @class = "form-control datepicker" } })
                        @Html.ValidationMessageFor(model => model.Begindatum, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Einddatum, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">


                        @Html.EditorFor(model => model.Einddatum, new { htmlAttributes = new { @class = "form-control datepicker" } })
                        @Html.ValidationMessageFor(model => model.Einddatum, "", new { @class = "text-danger" })

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Inschrijfdatum, "Uiterste Inschrijfdatum", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Inschrijfdatum, new { htmlAttributes = new { @class = "form-control datepicker" } })
                        @Html.ValidationMessageFor(model => model.Inschrijfdatum, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.InschrijfgeldEnkel, "Inschrijfgeld Enkel", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.InschrijfgeldEnkel, new { htmlAttributes = new { @class = "form-control " } })
                        @Html.ValidationMessageFor(model => model.InschrijfgeldEnkel, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.InschrijfgeldDubbel, "Inschrijfgeld Dubbel", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.InschrijfgeldDubbel, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.InschrijfgeldDubbel, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="toernooiCreateRight">
                <div class="form-group">
                    @Html.LabelFor(model => model.Organisatie, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Organisatie, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Organisatie, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Bondsvertegenwoordiger, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Bondsvertegenwoordiger, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Bondsvertegenwoordiger, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.TellingID, "Puntentelling", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("TellingID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TellingID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.GewonnenGames, "Best-of", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("GewonnenGames", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.GewonnenGames, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Tijdlimiet, "Tijdlimiet Wedstrijden", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Tijdlimiet, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Tijdlimiet, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Tafels, "Aantal Tafels", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Tafels, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Tafels, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>


            <div class="toernooiCreateMiddel"></div>

            <div class="toernooiCreateLeft">
         
                    <h4>Kies een leeftijdscategorie</h4>
                    <hr />
                    <div class="form-group">
                        @Html.LabelFor(model => model.Categorie, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10 ">
                            @Html.DropDownList("Categorie", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Categorie, "", new { @class = "text-danger" })
                       
                            
                        </div>

                        <div class="col-md-10" id="checkbox" >
                            @Html.Label("Met Niveaus")
                            @Html.CheckBoxFor(model => model.Niveaus, false)
                        </div>
                    </div>
         
            </div>
            <div class="toernooiCreateRight toernooiVormCreate">
                <h4>Kies een toernooivorm</h4>
                <hr />
                <div class="form-group">
                      @Html.DropDownList("toernooivormen", null, "", htmlAttributes: new { @class = "form-control" })                 
                </div>
                <div class="toernooiVormCreateP">
                    @Html.HiddenFor(model => model.Toernooivorm1)
                    @Html.HiddenFor(model => model.Toernooivorm2)
                    @Html.HiddenFor(model => model.Toernooivorm3)
                    @Html.HiddenFor(model => model.Toernooivorm4)
                    <p id="toernooivorm1text"></p><input type="button" id="button1" class="closeBtnToernooivorm" value="X" />
                    <p id="toernooivorm2text"></p><input type="button" id="button2" class="closeBtnToernooivorm" value="X" />
                    <p id="toernooivorm3text"></p><input type="button" id="button3" class="closeBtnToernooivorm" value="X" />
                    <p id="toernooivorm4text"></p><input type="button" id="button4" class="closeBtnToernooivorm" value="X" />
                </div>
            </div>
            <div class=""></div>

            <div class="toernooiCreateButton">
                <div class="form-inline">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <a href="/Toernooi">
                                <input type="button" value="Cancel" class="btn btn-default" />
                            </a>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

<script src="~/Scripts/toernooi.js"></script>
}

NTTB GELRE/Views/Toernooi/Delete.cshtml
@model NTTB_GELRE.Models.Toernooi

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Toernooi</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Toernooinaam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Toernooinaam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Begindatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Begindatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Einddatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Einddatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Inschrijfdatum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Inschrijfdatum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InschrijfgeldEnkel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InschrijfgeldEnkel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InschrijfgeldDubbel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InschrijfgeldDubbel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Organisatie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Organisatie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bondsvertegenwoordiger)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bondsvertegenwoordiger)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GewonnenGames)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GewonnenGames)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tijdlimiet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tijdlimiet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tafels)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tafels)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Locatie.Adres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Locatie.Adres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Puntentelling.TellingID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Puntentelling.TellingID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>