NTTB GELRE/Controllers/GameScoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Web.Mvc;
using NTTB_GELRE.Models;
using System.Data.SqlClient;
using System.Data.Entity.Core.EntityClient;
using System.Configuration;
using System.Web.SessionState;
using System.Diagnostics;

namespace NTTB_GELRE.Controllers
{
    public class GameScoreController : Controller
    {
        NTTBGELREEntities db = new NTTBGELREEntities();
        // GET: GameScore
        public ActionResult Index()
        {
            var date = System.DateTime.Now;
            String userEmail = Convert.ToString(Session["Werknemer"]);
            var user = db.Werknemer.FirstOrDefault(u => u.Mailadres == userEmail);

     
            var view = new List<Wedstrijd>();
            foreach (var toernooi in user.Toernooi)
            {
                var a = db.Wedstrijd.Where(o => o.ToernooiID.Equals(toernooi.ToernooiID)).ToList();
                foreach (var t in a)
                {
                    view.Add(new Wedstrijd()
                    {
                        Tafelnummer = t.Tafelnummer,
                        Begintijd = t.Begintijd,
                        Speler1 = t.Speler1,
                        Speler2 = t.Speler2,
                        WedstrijdID = t.WedstrijdID,
                        CategorieID = t.CategorieID,
                        ToernooiID = t.ToernooiID
                    });
                }
            }          
           
            ViewData["Wedstrijden2"] = view;

            return View();
        }

        public ActionResult Opgave(Wedstrijd wedstrijd)
        {
            int? opgave = wedstrijd.Opgave;
            if (opgave != null)
            {
                System.Data.Common.DbConnection dbConn = db.Database.Connection;
                System.Data.SqlClient.SqlConnection sc = (System.Data.SqlClient.SqlConnection)dbConn;
                string adoConnStr = sc.ConnectionString;

                using (SqlConnection connection = new SqlConnection(adoConnStr))
                {
                    connection.Open();
                    // Stored procedure naam = inschrijving
                    SqlCommand cmd = new SqlCommand("sp_GameWinnaar", connection);
                    cmd.CommandType = CommandType.StoredProcedure;

                    // Paramaters voor de stored procedure
                    cmd.Parameters.AddWithValue("@CategorieID", wedstrijd.CategorieID);
                    cmd.Parameters.AddWithValue("@ToernooiID", wedstrijd.ToernooiID);
                    cmd.Parameters.AddWithValue("@WedstrijdID", wedstrijd.WedstrijdID);
                    cmd.Parameters.AddWithValue("@Opgave", opgave);

                    cmd.ExecuteNonQuery();
                }
            }

            return View();
        }

        [HttpGet]
        public ActionResult Score(int? id, int? idCat, int tID)
        {
            var query = db.Wedstrijd.First(pv => pv.WedstrijdID == (id) & pv.CategorieID == (idCat) & pv.ToernooiID == (tID));

            ViewBag.Winnaar = false;
            if (!String.IsNullOrEmpty(Convert.ToString(query.Winnaar)))
            {
                ViewBag.Winnaar = true;
            }
            var game = (from g in db.Gamescores
                        where g.WedstrijdID == id & g.CategorieID == idCat & g.ToernooiID == tID 
                        select new
                        {
                            ToernooiID = g.ToernooiID,
                            CategorieID = g.CategorieID,
                      
                            WedstrijdID = g.WedstrijdID,
                            Punten1 = g.Punten1,
                            Punten2 = g.Punten2,
                            Game = g.Game

                        });

            var view = new List<Gamescores>();
            foreach (var g in game)
            {
                view.Add(new Gamescores()
                {

                    ToernooiID = g.ToernooiID,
                    CategorieID = g.CategorieID,
     
                    WedstrijdID = g.WedstrijdID,
                    Punten1 = g.Punten1,
                    Punten2 = g.Punten2,
                    Game = g.Game


                });
            }
            ViewData["Game"] = view;

            return View(query);
        }

        [HttpPost]
        public ActionResult Score(Gamescores gameScore)
        {
            ViewBag.Winnaar = false;
            if (ModelState.IsValid)
            {

                // Stored procedure

                System.Data.Common.DbConnection dbConn = db.Database.Connection;
                System.Data.SqlClient.SqlConnection sc = (System.Data.SqlClient.SqlConnection)dbConn;
                string adoConnStr = sc.ConnectionString;
                var toernooi = db.Toernooi.Find(gameScore.ToernooiID);


                using (SqlConnection connection = new SqlConnection(adoConnStr))
                {
                    connection.Open();
                    // Stored procedure naam = inschrijving
                    SqlCommand cmd = new SqlCommand("sp_GameScore", connection);
                    cmd.CommandType = CommandType.StoredProcedure;

                    // Paramaters voor de stored procedure
                    cmd.Parameters.AddWithValue("@CategorieID", gameScore.CategorieID);
                    cmd.Parameters.AddWithValue("@ToernooiID", gameScore.ToernooiID);
                    cmd.Parameters.AddWithValue("@WedstrijdID", gameScore.WedstrijdID);
                    cmd.Parameters.AddWithValue("@Punten1", gameScore.Punten1);
                    cmd.Parameters.AddWithValue("@Punten2", gameScore.Punten2);
                    cmd.Parameters.AddWithValue("@set_", toernooi.GewonnenGames);
                    cmd.Parameters.AddWithValue("@punttelling_", toernooi.Puntentelling.Tot);
                    cmd.ExecuteNonQuery();
                }
            }
            var query = db.Wedstrijd.First(pv => pv.WedstrijdID == (gameScore.WedstrijdID) & pv.CategorieID == (gameScore.CategorieID) & pv.ToernooiID == (gameScore.ToernooiID) );
            if (!String.IsNullOrEmpty(Convert.ToString(query.Winnaar)))
            {
                ViewBag.Winnaar = true;
            }
            var game = (from g in db.Gamescores
                        where g.WedstrijdID == gameScore.WedstrijdID & g.CategorieID == gameScore.CategorieID & g.ToernooiID == gameScore.ToernooiID
                        select new
                        {
                            ToernooiID = g.ToernooiID,
                            CategorieID = g.CategorieID,
                            WedstrijdID = g.WedstrijdID,
                            Punten1 = g.Punten1,
                            Punten2 = g.Punten2,
                            Game = g.Game

                        });

            var view = new List<Gamescores>();
            foreach (var g in game)
            {
                view.Add(new Gamescores()
                {

                    ToernooiID = g.ToernooiID,
                    CategorieID = g.CategorieID,
                    WedstrijdID = g.WedstrijdID,
                    Punten1 = g.Punten1,
                    Punten2 = g.Punten2,
                    Game = g.Game


                });
            }
            ViewData["Game"] = view;
            return View(query);
        }
    }
}

NTTB GELRE/Controllers/ToernooiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NTTB_GELRE.Models;
using System.Data.SqlClient;
using System.Data.Entity.Core.EntityClient;
using System.Configuration;
using System.Web.SessionState;

namespace NTTB_GELRE.Controllers
{
    public class ToernooiController : Controller
    {
        private NTTBGELREEntities db = new NTTBGELREEntities();


        public ToernooiController(){

                   
         
        }
        // GET: Toernooi
        public ActionResult Index()
        {
            
            var toernoois = db.Toernooi.Include(t => t.Locatie).Include(t => t.Puntentelling);
            return View(toernoois.ToList());
        }

      
        // GET: Toernooi/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Toernooi toernooi = db.Toernooi.Find(id);
            if (toernooi == null)
            {
                return HttpNotFound();
            }
            return View(toernooi);
        }

        // GET: Toernooi/Create
        public ActionResult Create()
        {
            ViewBag.addCar = false;
            //ViewData["categorie"] = db.Categorie.ToList();
            ViewBag.Locatienaam = new SelectList(db.Locatie, "Locatienaam", "Locatienaam");

            
            //ViewBag.Locatienaam = new SelectList(db.Locatie, "Locatienaam", "Locatienaam");

            var leeftijdsgroepen = db.Categorie.Select(c => c.Leeftijdsgroep).Distinct();
            ViewBag.Categorie = new SelectList(leeftijdsgroepen);
       
            ViewBag.TellingID = new SelectList(db.Puntentelling, "TellingID", "Tot");

            List<SelectListItem> puntentellingen = new List<SelectListItem>();
            puntentellingen.Add(new SelectListItem { Text = "1", Value = "1" });
            puntentellingen.Add(new SelectListItem { Text = "3", Value = "3" });
            puntentellingen.Add(new SelectListItem { Text = "5", Value = "5" });
            puntentellingen.Add(new SelectListItem { Text = "7", Value = "7" });
            puntentellingen.Add(new SelectListItem { Text = "9", Value = "9" });
            puntentellingen.Add(new SelectListItem { Text = "11", Value = "11" });

            ViewBag.GewonnenGames = puntentellingen;

            var toernooivormenLst = new List<string>();

            var toernooivormenQry = (from t in db.Toernooivorm
                                     select t.Toernooivorm1);

            toernooivormenLst.AddRange(toernooivormenQry.Distinct());
            ViewBag.toernooivormen = new SelectList(toernooivormenLst);

            return View();
        }

        // POST: Toernooi/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ToernooiAanmaken toernooi)
        {
            if (ModelState.IsValid)
            {

                // Stored procedure
                NTTBGELREEntities ctx = new NTTBGELREEntities();
                System.Data.Common.DbConnection dbConn = ctx.Database.Connection;
                System.Data.SqlClient.SqlConnection sc = (System.Data.SqlClient.SqlConnection)dbConn;
                string adoConnStr = sc.ConnectionString;

                using (SqlConnection connection = new SqlConnection(adoConnStr))
                {
                    connection.Open();
                    // Stored procedure naam = inschrijving
                    SqlCommand cmd = new SqlCommand("spSchemasAanmaken", connection);
                    cmd.CommandType = CommandType.StoredProcedure;

                    // Paramaters voor de stored procedure
                    cmd.Parameters.AddWithValue("@Locatienaam", toernooi.Locatienaam);
                    cmd.Parameters.AddWithValue("@TellingID", toernooi.TellingID);
                    cmd.Parameters.AddWithValue("@Toernooinaam", toernooi.Toernooinaam);
                    cmd.Parameters.AddWithValue("@Begindatum", toernooi.Begindatum);
                    cmd.Parameters.AddWithValue("@Einddatum", toernooi.Einddatum);
                    cmd.Parameters.AddWithValue("@Inschrijfdatum", toernooi.Inschrijfdatum);
                    cmd.Parameters.AddWithValue("@InschrijfGeldEnkel", toernooi.InschrijfgeldEnkel);
                    cmd.Parameters.AddWithValue("@InschrijfGeldDubbel", toernooi.InschrijfgeldDubbel);
                    cmd.Parameters.AddWithValue("@Organisatie", toernooi.Organisatie);
                    cmd.Parameters.AddWithValue("@Bondsvertegenwoordiger", toernooi.Bondsvertegenwoordiger);
                    cmd.Parameters.AddWithValue("@GewonnenGames", toernooi.GewonnenGames);
                    cmd.Parameters.AddWithValue("@Tijdlimiet", toernooi.Tijdlimiet);
                    cmd.Parameters.AddWithValue("@Tafels", toernooi.Tafels);
                    cmd.Parameters.AddWithValue("@Categorie", toernooi.Categorie);
                    cmd.Parameters.AddWithValue("@Niveaus", toernooi.Niveaus);
                    cmd.Parameters.AddWithValue("@Toernooivorm1", toernooi.Toernooivorm1);
                    cmd.Parameters.AddWithValue("@Toernooivorm2", toernooi.Toernooivorm2);
                    cmd.Parameters.AddWithValue("@Toernooivorm3", toernooi.Toernooivorm3);
                    cmd.Parameters.AddWithValue("@Toernooivorm4", toernooi.Toernooivorm4);
                    
                    
                    cmd.ExecuteNonQuery();
                }

                return RedirectToAction("Index","Home");
            }
            ViewBag.Locatienaam = new SelectList(db.Locatie, "Locatienaam", "Locatienaam");


            //ViewBag.Locatienaam = new SelectList(db.Locatie, "Locatienaam", "Locatienaam");

            var leeftijdsgroepen = db.Categorie.Select(c => c.Leeftijdsgroep).Distinct();
            ViewBag.Categorie = new SelectList(leeftijdsgroepen);
            
            ViewBag.TellingID = new SelectList(db.Puntentelling, "TellingID", "Tot");
            List<SelectListItem> puntentellingen = new List<SelectListItem>();
            puntentellingen.Add(new SelectListItem { Text = "1", Value = "1" });
            puntentellingen.Add(new SelectListItem { Text = "3", Value = "3" });
            puntentellingen.Add(new SelectListItem { Text = "5", Value = "5" });
            puntentellingen.Add(new SelectListItem { Text = "7", Value = "7" });
            puntentellingen.Add(new SelectListItem { Text = "9", Value = "9" });
            puntentellingen.Add(new SelectListItem { Text = "11", Value = "11" });

            ViewBag.GewonnenGames = puntentellingen;

            var toernooivormenLst = new List<string>();

            var toernooivormenQry = (from t in db.Toernooivorm
                                     select t.Toernooivorm1);

            toernooivormenLst.AddRange(toernooivormenQry.Distinct());
            ViewBag.toernooivormen = new SelectList(toernooivormenLst);

            return View(toernooi);
        }

        // GET: Toernooi/CreateStepTwo
        public ActionResult CreateStepTwo(int toernooiID, string leeftijdsgroep)
        {
            var Categorieen = from c in db.Categorie
                              where c.Leeftijdsgroep == leeftijdsgroep
                              select c;
            return View(Categorieen.ToList());
        }

        // GET: Toernooi/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Toernooi toernooi = db.Toernooi.Find(id);
            if (toernooi == null)
            {
                return HttpNotFound();
            }
            ViewBag.Locatienaam = new SelectList(db.Locatie, "Locatienaam", "Adres", toernooi.Locatienaam);
            ViewBag.TellingID = new SelectList(db.Puntentelling, "TellingID", "TellingID", toernooi.TellingID);
            return View(toernooi);
        }

        // POST: Toernooi/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ToernooiID,Locatienaam,TellingID,Toernooinaam,Begindatum,Einddatum,Inschrijfdatum,InschrijfgeldEnkel,InschrijfgeldDubbel,Organisatie,Bondsvertegenwoordiger,GewonnenGames,Tijdlimiet,Tafels")] Toernooi toernooi)
        {
            if (ModelState.IsValid)
            {
                db.Entry(toernooi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
  
            ViewBag.Locatienaam = new SelectList(db.Locatie, "Locatienaam", "Adres", toernooi.Locatienaam);
            ViewBag.TellingID = new SelectList(db.Puntentelling, "TellingID", "TellingID", toernooi.TellingID);
            return View(toernooi);
        }

        // GET: Toernooi/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Toernooi toernooi = db.Toernooi.Find(id);
            if (toernooi == null)
            {
                return HttpNotFound();
            }
            return View(toernooi);
        }

        // POST: Toernooi/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Toernooi toernooi = db.Toernooi.Find(id);

NTTB GELRE/Views/GameScore/Index.cshtml
@using NTTB_GELRE.Models;

@{

    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Wedstrijd> toernooi = ViewData["Wedstrijden2"] as List<Wedstrijd>;

}


@Html.Partial("Toernooi", toernooi)

NTTB GELRE/Views/GameScore/MatchSet.cshtml
@model IEnumerable<NTTB_GELRE.Models.Gamescores>
<h4>GameScore</h4>
<table class="table GameScoreTabel">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Punten1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Punten2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Game)
        </th>
      
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Punten1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Punten2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Game)
        </td>
        
    </tr>
}

</table>

NTTB GELRE/Views/GameScore/Score.cshtml
@model NTTB_GELRE.Models.Wedstrijd
@using NTTB_GELRE.Models;

@{
    ViewBag.Title = "Score";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Gamescores> GameSets = ViewData["Game"] as List<Gamescores>;
}

<h2>Score</h2>

<div id="wedstijdenScores">
    <div class="wedstrijden">
        <h4>Wedstrijd</h4>
        <div class="wedstrijdenOpgave">
            @using (Html.BeginForm("Opgave", "GameScore", "Opgave"))
            {
                <input type="hidden" value=@Html.DisplayFor(model => model.WedstrijdID) name=@Html.DisplayNameFor(model => model.WedstrijdID) />
                <input type="hidden" value=@Html.DisplayFor(model => model.CategorieID) name=@Html.DisplayNameFor(model => model.CategorieID) />
                <input type="hidden" value=@Html.DisplayFor(model => model.SchemaDeel) name=@Html.DisplayNameFor(model => model.SchemaDeel) />
                <input type="hidden" value=@Html.DisplayFor(model => model.ToernooiID) name=@Html.DisplayNameFor(model => model.ToernooiID) />

                <label for="test">@Html.DisplayFor(model => model.Deelnemer.Speler.Voornaam) @Html.DisplayFor(model => model.Deelnemer.Speler.Bondsnummer) </label>
                <input type="radio" name="OpgaveSpeler" value=@Html.DisplayFor(model => model.Speler1)>
                <label for="test">@Html.DisplayFor(model => model.Deelnemer1.Speler.Voornaam)  @Html.DisplayFor(model => model.Deelnemer1.Speler.Bondsnummer)</label>
                <input type="radio" name="OpgaveSpeler" value=@Html.DisplayFor(model => model.Speler2)>
                <input class="btn-warning" type="submit" value="Opgave" />
            }
        </div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Winnaar)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Winnaar)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Opgave)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Opgave)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Kwalificatie1)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Kwalificatie1)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Kwalificatie2)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Kwalificatie2)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Ronde)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Ronde)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Begintijd)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Begintijd)
            </dd>

            <dt>
                Speler 1
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Deelnemer.Speler.Voornaam) @Html.DisplayFor(model => model.Deelnemer.Speler.Achternaam)
                @Html.DisplayFor(model => model.Deelnemer.Speler.Bondsnummer)
            </dd>

            <dt>
                Speler 2
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Deelnemer1.Speler.Voornaam) @Html.DisplayFor(model => model.Deelnemer1.Speler.Achternaam)
                @Html.DisplayFor(model => model.Deelnemer1.Speler.Bondsnummer)


            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Tafel.Tafelnummer)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Tafel.Tafelnummer)
            </dd>

          
        </dl>
    </div>
    @Html.Partial("MatchSet", GameSets)
    <div id="score">
        @using (Html.BeginForm())
        {

            @Html.HiddenFor(model => model.ToernooiID)
            @Html.HiddenFor(model => model.Toernooicategorie.Toernooi.GewonnenGames)
            @Html.HiddenFor(model => model.Toernooicategorie.Toernooi.Puntentelling)
            @Html.HiddenFor(model => model.SchemaDeel)
            @Html.HiddenFor(model => model.CategorieID)
            @Html.HiddenFor(model => model.WedstrijdID)

            <div class="ScoreButton">
                <h2>Speler 1</h2>
                <input class=" btn btn-danger" type="submit" value="-1" name="Punten1" />
                <input class=" btn btn-success" type="submit" value="1" name="Punten1" />

            </div>
            <div class="ScoreButton">
                <h2>Speler 2</h2>
                <input class=" btn btn-danger" type="submit" value="-1" name="Punten2" />
                <input class=" btn btn-success" type="submit" value="1" name="Punten2" />.


            </div>
        }

    </div>
</div>

@if (ViewBag.Winnaar)
{
    <div id="Winnaar">
        <script>

            (function () {
                var doc = document.getElementById("wedstijdenScores");
                doc.className = "blur"
                var doc1 = document.getElementById("Winnaar");
                doc1.className = "noBlur"

            })();
        </script>

        @if (@Html.DisplayFor(model => model.Winnaar) == @Html.DisplayFor(model => model.Deelnemer.Speler.SpelerID))
        {
            <h4>De winnaar is @Html.DisplayFor(model => model.Deelnemer.Speler.Voornaam) @Html.DisplayFor(model => model.Deelnemer.Speler.Bondsnummer)</h4>
        }
        else
        {
            <h4>De winnaar is @Html.DisplayFor(model => model.Deelnemer1.Speler.Voornaam) @Html.DisplayFor(model => model.Deelnemer1.Speler.Bondsnummer)</h4>
        }
        <button class="btn btn-danger" id="WinnaarBtnAnnuleer">Annuleer</button>
        <button class="btn btn-success" id="WinnaarBtnGo">@Html.ActionLink("Terug naar lijst", "Index")</button>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

    <script src="~/Scripts/wedstrijden.js"></script>
}

NTTB GELRE/Views/GameScore/Toernooi.cshtml
@model IEnumerable<NTTB_GELRE.Models.Wedstrijd>
@using NTTB_GELRE.Controllers;

<div class="toernooiGrootScherm">
    <h2>Toernooi Overzicht</h2>
    <table class="table ">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Begintijd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tafelnummer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Speler1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Speler2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategorieID)
            </th>
            <th>
            </th>
        </tr>

        @foreach (var item in Model)
        {
            @Html.HiddenFor(modelItem => item.WedstrijdID)
            @Html.HiddenFor(modelItem => item.ToernooiID)
            @Html.HiddenFor(modelItem => item.SchemaDeel)
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Begintijd)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tafelnummer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Speler1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Speler2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategorieID)
                </td>
                <td>
                    <button class="btn btn-success">  @Html.ActionLink("Kies", "Score", new { id = item.WedstrijdID, idCat = item.CategorieID, tID = item.ToernooiID })</button>   
                </td>
            </tr>
        }
    </table>
</div>

@*<!-- Static navbar -->
<div class="navbar navbar-inverse ToernooiBar" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Toernooi</a>
    </div>
    <div class="navbar-collapse1 collapse">
        <ul class="nav navbar-nav ToernooiBarUL">
            @foreach (var item in Model)
            {
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">@Html.DisplayFor(modelItem => item.Toernooinaam) <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        @foreach (var i in item.Tafel)
                        {
                            <li>
                                @Html.ActionLink("Tafel " + @Convert.ToString(i.Tafelnummer), "Edit", new { id = i.Tafelnummer })
                            </li>
                        }
                    </ul>
                </li>
            }
        </ul>

    </div><!--/.nav-collapse -->
</div>*@

@*<link href="~/Content/smartmenu/jquery.smartmenus.bootstrap.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>

<script src="~/Scripts/smartmenu/jquery.smartmenus.bootstrap.min.js"></script>
<script src="~/Scripts/smartmenu/jquery.smartmenus.js"></script>

<!-- SmartMenus jQuery plugin -->
<script type="text/javascript" src="../jquery.smartmenus.js"></script>

<!-- SmartMenus jQuery Bootstrap Addon -->
<script type="text/javascript" src="../addons/bootstrap/jquery.smartmenus.bootstrap.js"></script>*@